DROP TABLE IF EXIST ZEPTO;

CREATE TABLE zepto (
  sku_id SERIAL PRIMARY KEY,
  category VARCHAR(120),
  name VARCHAR(150) NOT NULL,
  mrp NUMERIC(8,2),
  discountPercent NUMERIC(5,2),
  availableQuantity INTEGER,
  discountedSellingPrice NUMERIC(8,2),
  weightInGms INTEGER,
  outOfStock BOOLEAN,
  quantity INTEGER
);

-- DATA EXPLORATION

-- ROW COUNT

SELECT COUNT(*)
FROM ZEPTO;

-- SAMPLE THE DATA

SELECT *
FROM ZEPTO
LIMIT 10;

-- null values

SELECT *
FROM ZEPTO
WHERE NAME IS NULL OR
	  CATEGORY IS NULL OR
	  MRP IS NULL OR
	  DISCOUNTPERCENT IS NULL OR
	  AVAILABLEQUANTITY IS NULL OR
	  DISCOUNTEDSELLINGPRICE IS NULL OR
	  WEIGHTINGMS IS NULL OR
	  OUTOFSTOCK IS NULL OR
	  QUANTITY IS NULL;

-- TYPES OF PRODUCTS
SELECT DISTINCT CATEGORY
FROM ZEPTO
ORDER BY CATEGORY;

-- PRODUCT IN STOCK OR OUT OF STOCK
SELECT OUTOFSTOCK , COUNT(SKU_ID)
FROM ZEPTO
GROUP BY OUTOFSTOCK;

-- PRODUCT NAMES PRESEMT MULTIPLE TIMES
SELECT NAME, COUNT(SKU_ID) AS "NUMBER OF SKU'S"
FROM ZEPTO
GROUP BY NAME
HAVING COUNT(SKU_ID) > 1
ORDER BY COUNT(SKU_ID) DESC;

-- DATA CLEANING

-- PRODUCTS WITH PRICE = 0
SELECT *
FROM ZEPTO
WHERE MRP = 0 OR
	  DISCOUNTEDSELLINGPRICE = 0;

DELETE 
FROM ZEPTO
WHERE MRP = 0;



-- CONVERT THE MRP ININDIAN STANDERD 
UPDATE ZEPTO
SET MRP = MRP/100.0 , DISCOUNTEDSELLINGPRICE = MRP/100.0;

SELECT * FROM ZEPTO
ORDER BY SKU_ID ASC;


-- Q1. FIND THE TOP 10 BEST-VALUES PRODUCTS ON THE DISCOUNT PRICE.

SELECT DISTINCT NAME , MRP , DISCOUNTPERCENT
FROM ZEPTO
ORDER BY DISCOUNTPERCENT DESC
LIMIT 10;


-- Q2. WHAT ARE THE PRODUCTS WITH HIGH MRP BUT OUT OF STOCK.

SELECT DISTINCT NAME , MRP
FROM ZEPTO
WHERE OUTOFSTOCK = TRUE AND
	   MRP > 300
ORDER BY MRP DESC;

-- Q3. CALCULATE THE ESTIMATED REVENUE FOR EACH CATEGORY.
SELECT CATEGORY,
SUM(DISCOUNTEDSELLINGPRICE * AVAILABLEQUANTITY) AS TOTAL_REVENUE
FROM ZEPTO
GROUP BY CATEGORY
ORDER BY TOTAL_REVENUE ;
-- Q4. FIND ALL THE PROSUCTS WHERE MRP IS GREATER THEN 500 AND DISCOUNT LESS THEN 10%.
SELECT DISTINCT NAME , MRP,DISCOUNTPERCENT
FROM ZEPTO
WHERE MRP > 500 AND
	  DISCOUNTPERCENT < 10
ORDER BY MRP DESC , DISCOUNTPERCENT DESC;

-- Q5. IDENTIFY THE TOP FIVE CATEGORIES OFFERING THE HIGHERST AVERAGE DISCOIUNT PERCENTAGE.
SELECT CATEGORY ,
ROUND(AVG(DISCOUNTPERCENT),2) AS AVG_DISCOUNT
FROM ZEPTO
GROUP BY CATEGORY
ORDER BY AVG_DISCOUNT DESC
LIMIT 5;

-- Q6. FIND THE PRICE PER GRAM FOR PRODUCTS ABOVE 100G AND SORT BY BEST VALUES.
SELECT DISTINCT NAME , WEIGHTINGMS ,DISCOUNTEDSELLINGPRICE,
ROUND(DISCOUNTEDSELLINGPRICE / WEIGHTINGMS,2) AS PRICE_PER_GMS
FROM ZEPTO
WHERE WEIGHTINGMS >= 100
ORDER BY PRICE_PER_GMS;
-- Q7. GROUP THE PRODUCTS INTO CATEGORIES LIKE LOW , MEDIUM, HIGH.
SELECT DISTINCT name, weightInGms,
CASE WHEN weightInGms < 1000 THEN 'Low'
	WHEN weightInGms < 5000 THEN 'Medium'
	ELSE 'Bulk'
	END AS weight_category
FROM zepto;

-- Q8. WHAT IS THE TOTAL INVENTRY WEIGHT PER CATEGORY.
SELECT category,
SUM(weightInGms * availableQuantity) AS total_weight
FROM zepto
GROUP BY category
ORDER BY total_weight;




